version: 2.1

jobs:
  
  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/python-lz4
    steps:
      
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
              pip install --upgrade pip
              cd bindings/pydeck/requirements
              pip install --upgrade pip
              pip install -r requirements-dev.txt
              curl https://raw.github.com/creationix/nvm/master/install.sh | sh
              nvm install 10.16.0
              nvm use 10.16.0
              cd .. 
              pip install -e . --install-option "--build_all"
              pip install -e . --install-option "--build_all" --verbose
              pytest --cov=pydeck
              
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/python-lz4
    steps:
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             pip3 install --upgrade pip
             cd bindings/pydeck/requirements
             pip3 install --upgrade pip
             pip3 install -r requirements-dev.txt
             curl https://raw.github.com/creationix/nvm/master/install.sh | sh
             nvm install 10.16.0
             nvm use 10.16.0
             cd .. 
             pip3 install -e . --install-option "--build_all"
             pip3 install -e . --install-option "--build_all" --verbose
             pytest --cov=pydeck
workflows:
  version: 2
  python3.7:
    jobs:
      
      - build-medium-amd64
      - build-medium-arm64
